### DISCUSSION TITLE
publish looks for target/site/javadoc and doesn't find it

### DISCUSSION THREAD

**Discussion by steinarb** [MathieuSoysal/Javadoc-publisher.yml#48] [Q&A] [answered]
I had the following build for a java project:
```
name: modelstore CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent install coveralls:report sonar:sonar --file pom.xml --define repoToken=${{ secrets.COVERALLS_REPO_SECRET }} -Dsonar.projectKey=steinarb_modelstore -Dsonar.organization=steinarb -Dsonar.host.url=https://sonarcloud.io
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
and then I tried adding javadoc deploy, with the following changes:
```
name: modelstore CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent install coveralls:report sonar:sonar --file pom.xml --define repoToken=${{ secrets.COVERALLS_REPO_SECRET }} -Dsonar.projectKey=steinarb_modelstore -Dsonar.organization=steinarb -Dsonar.host.url=https://sonarcloud.io
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy javadoc
      uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        javadoc-branch: javadoc
        java-version: 11
        target-folder: javadoc # url will be https://<username>.github.io/<repo>/javadoc, This can be left as nothing to generate javadocs in the root folder.
        project: maven
        subdirectories: modelstore.services modelstore.backend
```

The build works but publish fails with the message:
```
Run if [ ! -d target/site/apidocs ]; then
cp: cannot stat 'modelstore.services/target/site/apidocs/': No such file or directory
Error: Process completed with exit code 1.
```

When running locally I have no modelstore.services/target/site directory, but I do have javadocs in modelstore.servies/target/apidocs/

Is it possible to make Javadoc-publisher fetch from there?
Or do I need to create the site directory with javadoc? (if so: how?)

Or do I need to do this javadoc deploy as an integrated part of the actual maven build?

Here is the project I'm trying this on (I'm currently in the process of replacing a no-longer-working travis-ci with github action: https://github.com/steinarb/modelstore

Thanks!
