### DISCUSSION TITLE
The task was successfully executed, but the branch was not created

### DISCUSSION THREAD

**Discussion by lunasaw** [MathieuSoysal/Javadoc-publisher.yml#53] [Q&A] [answered]
```
name: Deploy Javadoc

on:
  push:
    branches:
      - master
jobs:
  publish:
    environment: dep 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.SECRET_KEY }}
          javadoc-branch: javadoc
          java-version: 8
          target-folder: docs
          without-deploy: true
```

Hello, I would like to ask you a question. This task has been successfully executed but my branch has not been created. Is it my configuration proble

https://github.com/lunasaw/webdav-spring-boot-starter/actions/runs/4596969980/jobs/8119087725

**Comment by lunasaw** [comment]
```
name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    environment: dep
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.SECRET_KEY }}
          javadoc-branch: javadoc
          java-version: 17
          target-folder: docs

```


I use `  java-version: 17` can be work for me,  but I wanted to deploy using this link `https://YOUR-USERNAME.github.io/YOUR-REPO/docs/` and found it didn't work. github pages configuration can only use `/`and ` /docs`, I ues `without deploy : true ` ，Found also run successfully unable to see the commit information
