### DISCUSSION TITLE
Deploy reports success, but no Javadoc was actually published.

### DISCUSSION THREAD

**Discussion by Jannyboy11** [MathieuSoysal/Javadoc-publisher.yml#54] [Q&A] [answered]
Hi, thank you for creating action. I just have one problem and I don't know whether this is a bug, or I'm doing something wrong.
In my project [ScalaPluginLoader](https://github.com/Jannyboy11/ScalaPluginLoader) I use this action to generate javadoc for 4 out of the 8 maven modules using a custom command: `mvn package javadoc:aggregate -pl :ScalaPluginLoader,:ScalaLoader-Common,:ScalaLoader-Bukkit,:ScalaLoader-Paper`. This seems to work well - the Javadoc is generated and available on the `javadoc` branch, but the deployment to GitHub Pages is failing, despite [it's saying it succeeded](https://github.com/Jannyboy11/ScalaPluginLoader/actions/runs/4583993480/jobs/8095194624#step:7:1639). I expect the Javadoc to be available at https://Jannyboy11.github.io/ScalaPluginLoader/javadoc, but GitHub reports a 404.

I was hoping you would be able to assist me, thanks in advance!

My setup:
Project Layout (maven):
```
ScalaPluginLoader
+--ScalaLoader-Common
+--ScalaLoader-Bukkit
+--ScalaLoader-Paper
.... 4 more submodules for which I do not want to generate javadoc
```
GH actions workflow steps:
```yaml
      - name: Deploy Javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-distribution: temurin
          java-version: 20
          custom-command: 'mvn package javadoc:aggregate -pl :ScalaPluginLoader,:ScalaLoader-Common,:ScalaLoader-Bukkit,:ScalaLoader-Paper'
          target-folder: javadoc # url will be https://<username>.github.io/<repo>/javadoc, This can be left as nothing to generate javadocs in the root folder.
          project: maven # or gradle
```

<details>
   <summary>Logs</summary>

```logs
Run JamesIves/github-pages-deploy-action@v4.4.1

    ╭━━━╮╭╮╭╮╱╭╮╱╱╭╮╱╱╭━━━╮
    ┃╭━╮┣╯╰┫┃╱┃┃╱╱┃┃╱╱┃╭━╮┃
    ┃┃╱╰╋╮╭┫╰━╯┣╮╭┫╰━╮┃╰━╯┣━━┳━━┳━━┳━━╮
    ┃┃╭━╋┫┃┃╭━╮┃┃┃┃╭╮┃┃╭━━┫╭╮┃╭╮┃┃━┫━━┫
    ┃╰┻━┃┃╰┫┃╱┃┃╰╯┃╰╯┃┃┃╱╱┃╭╮┃╰╯┃┃━╋━━┃
    ╰━━━┻┻━┻╯╱╰┻━━┻━━╯╰╯╱╱╰╯╰┻━╮┣━━┻━━╯
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯
    ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╭━━━╮╱╱╭╮
    ╰╮╭╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱┃╭━╮┃╱╭╯╰╮
    ╱┃┃┃┣━━┳━━┫┃╭━━┳╮╱╭╮┃┃╱┃┣━┻╮╭╋┳━━┳━╮
    ╱┃┃┃┃┃━┫╭╮┃┃┃╭╮┃┃╱┃┃┃╰━╯┃╭━┫┃┣┫╭╮┃╭╮╮
    ╭╯╰╯┃┃━┫╰╯┃╰┫╰╯┃╰━╯┃┃╭━╮┃╰━┫╰┫┃╰╯┃┃┃┃
    ╰━━━┻━━┫╭━┻━┻━━┻━╮╭╯╰╯╱╰┻━━┻━┻┻━━┻╯╰╯
    ╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╭━╯┃
    ╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╰━━╯
    

    💖 Support: https://github.com/sponsors/JamesIves
    📣 Maintained by James Ives: https://jamesiv.es/

    🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/ScalaPluginLoader/ScalaPluginLoader
/usr/bin/git config user.name Jannyboy11
/usr/bin/git config user.email Jannyboy11@users.noreply.github.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/Jannyboy11/ScalaPluginLoader.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/Jannyboy11/ScalaPluginLoader.git refs/heads/javadoc
Creating worktree…
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD 9771d41)
/usr/bin/git checkout --orphan javadoc
Switched to a new branch 'javadoc'
Created the javadoc branch… 🔧
/usr/bin/git reset --hard
/usr/bin/git commit --no-verify --allow-empty -m Initial javadoc commit
[javadoc (root-commit) 08617fa] Initial javadoc commit
/usr/bin/chmod -R +rw /home/runner/work/ScalaPluginLoader/ScalaPluginLoader/target/site/apidocs
Creating target folder if it doesn't already exist… 📌
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/ScalaPluginLoader/ScalaPluginLoader/target/site/apidocs/. github-pages-deploy-action-temp-deployment-folder/javadoc --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
Checking if there are files to commit…
/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/qzqjyglyo
Switched to a new branch 'github-pages-deploy-action/qzqjyglyo'
/usr/bin/git commit -m Deploying to javadoc from @ Jannyboy11/ScalaPluginLoader@9771d41784cbc6ea874313f1fb815cdca81a711b 🚀 --quiet --no-verify
Force-pushing changes...
/usr/bin/git push --force ***github.com/Jannyboy11/ScalaPluginLoader.git github-pages-deploy-action/qzqjyglyo:javadoc
remote: 
remote: Create a pull request for 'javadoc' on GitHub by visiting:        
remote:      https://github.com/Jannyboy11/ScalaPluginLoader/pull/new/javadoc        
remote: 
To https://github.com/Jannyboy11/ScalaPluginLoader.git
 * [new branch]      github-pages-deploy-action/qzqjyglyo -> javadoc
Changes committed to the javadoc branch… 📦
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/qzqjyglyo
Reset branch 'github-pages-deploy-action/qzqjyglyo'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Completed deployment successfully! ✅

```
</details>
