### ISSUE TITLE
Add possibility to add custom command

### ISSUE THREAD

**Issue by MathieuSoysal** [MathieuSoysal/Javadoc-publisher.yml#17]
## Introduction

Currently, the GitHub Action uses a library injection to add JavaDoc inside the pom.

## Problem

With this solution, we can't config the GitHub Actions to use the custom JavaDoc library inside the current project.   
And we can't add arguments for the JavaDoc generation.

## Solution

We can add a custom command like this:

```yml
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.4
        with:
          custom-command: mvn javadoc:aggregate pl name
```
The resources to help the implementation:
- https://docs.github.com/en/actions/learn-github-actions/expressions
- https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
- https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
