### ISSUE TITLE
uploading javadocs to root directory instead of `javadocs/` folder

### ISSUE THREAD

**Issue by n-tdi** [MathieuSoysal/Javadoc-publisher.yml#35]
Hello! I was wondering if it was possible to allow the Javadoc's to have the option to be created in the root folder. 

I was looking at #27 and I think this may have already done what I need, but I am unsure of how to use it!

The reason why I would like this is because I have a domain `docs.example.com` and want to host the javadocs on the subdomain without having it to be `docs.example.com/javadocs`

This would be really appreciated!

**Comment by n-tdi** [comment]
I was able to accomplish this myself! 
By leaving the target directory blank it would generate to the root one.

```yml
name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 17
          target-folder:  
          project: maven
          custom-command: mvn javadoc:javadoc
```
