### ISSUE TITLE
Customization of the folder destination of the generated Javadoc

### ISSUE THREAD

**Issue by MathieuSoysal** [MathieuSoysal/Javadoc-publisher.yml#49]
## Introduction

Currently, the generated Javadoc is got by default from [`target/site/apidocs`](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/9aa33c7012af892461ce08cea810f51e6f7fc21c/action.yml#L117) for the *Maven* project and [`build/docs/javadoc`](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/9aa33c7012af892461ce08cea810f51e6f7fc21c/action.yml#L127) for the *Gradle* project.

## Problem

But sometimes the project of the user doesn't generate the Javadoc to these folders, in this case, the GitHub Actions doesn't work.

Example of the problem: #48 

## Solution

To resolve this we can a new input to the GitHub Action [here](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/9aa33c7012af892461ce08cea810f51e6f7fc21c/action.yml#L7-L62)

To add the possibility to customize [javadoc-source-folder for maven](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/9aa33c7012af892461ce08cea810f51e6f7fc21c/action.yml#L117) and [javadoc-source-folder for gradle](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/9aa33c7012af892461ce08cea810f51e6f7fc21c/action.yml#L127).

###  Example of use :

```yaml
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy javadoc
      uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        javadoc-branch: javadoc
        java-version: 11
        target-folder: javadoc # url will be https://<username>.github.io/<repo>/javadoc, This can be left as nothing to generate javadocs in the root folder.
        project: maven
        subdirectories: modelstore.services modelstore.backend
        javadoc-source-folder: target/apidocs/
```

#### The feature in question:
```yaml
        javadoc-source-folder: target/apidocs/
```

### Note for add this
To add this feature we need to change all occurrences of this folder with the GitHub Action input inside [these lines](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/9aa33c7012af892461ce08cea810f51e6f7fc21c/action.yml#L94-L108)
