### ISSUE TITLE
Subdirectiories with Gradle and `java-source-folder` not set are looking for docs on the wrong path

### ISSUE THREAD

**Issue by notusedusername** [MathieuSoysal/Javadoc-publisher.yml#93]
## Summary

The default `javadoc-source-folder` is the one where Maven generates the files. The step [Hande subdirectories for GitHub Pages](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/main/action.yml#L90) creates a `common directory` to copy all docs into `separate target subdirectories` from the specified `source subdirectories/${{javadoc-source-folder}}` ([L#101](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/main/action.yml#L101)).

However as the default `javadoc-source-folder` is the Maven-specific path regardless the `project` input, the step tries to gather the docs from the wrong path when using `subdirectories` with default `javadoc-source-folder`.

If no `subdirectories` are specified, then the action works fine because it'll replace the default in this [step](https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/main/action.yml#L109).

## Workaround

Managed to mitigate the issue temporarily by specifying the source folder manually like this:

```yaml
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc-generated
          java-version: ${{ env.JAVA_VERSION }}
          java-distribution: ${{ env.JAVA_DISTRO }}
          target-folder: javadoc
          project: gradle
          subdirectories: my-gradle-subproject
          # Sets the source folder to Gradle's default. Mitigates a bug in the called action.
          javadoc-source-folder: build/docs/javadoc
```
